export default [
  // { path: '/', name: 'Portal', component: () => import('../page/Portal.vue') },
  { path: '/schedule/*', name: 'schedule', component: () => import('../page/Schedule.vue') },
  // { path: '/live/*', name: 'live', component: () => import('../page/live.vue') },
  // { path: '/sports/*', name: 'sports', component: () => import('../page/sports.vue') },
  // { path: '/topic/*', name: 'topic', component: () => import('../page/Topic.vue') },
  // { path: '/news/*', name: 'news', component: () => import('../page/News.vue') },
  // { path: '/videonews/*', name: 'videonews', component: () => import('../page/VideoNews.vue') },
  // { path: '/video/*', name: 'video', component: () => import('../page/video.vue') },
  // { path: '/images/*', name: 'images', component: () => import('../page/Images.vue') },
  // { path: '/shortvideonews/*', name: 'shortvideonews', component: () => import('../page/ShortVideoNews.vue') },
  // { path: '/shortvideolist', name: 'shortvideolist', component: () => import('../page/ShortVideoList.vue') },
  // { path: '/shortvideo/*', name: 'shortvideo', component: () => import('../page/ShortVideo.vue') },
  // { path: '/matchdata', name: 'matchdataredirect', component: () => import('../page/MatchData.vue') },
  // { path: '/matchdata/:tabMatchId/:component/:tabSportItemId', name: 'matchdata', component: () => import('../page/MatchData.vue') },
  // { path: '/livelist', name: 'livelist', component: () => import('../page/liveList.vue') },
  // { path: '/post', name: 'post', component: () => import('../page/post.vue') },
  // { path: '/postroom/*', name: 'postroom', component: () => import('../page/postroom.vue') },
  // { path: '/dailyshare/*', name: 'dailyshare', component: () => import('../page/DailyShare.vue') },
  // { path: '/animlive/*', name: 'animlive', component: () => import('../page/animlive.vue') },
  // { path: '/bixin/index', name: 'bixin', component: () => import('../page/bixin/index.vue') },
  // { path: '/matchvideo/:videoid', name: 'videoDetail', component: () => import('../page/videoDetail/index.vue') },
  // { path: '/nbalive/*', name: 'nbalive', component: () => import('../page/NBALive.vue') },
  // { path: '/downloadVideo', name: 'downloadVideo', component: () => import('../page/downLoadVideo/index.vue') },
  // { path: '/404.html', name: 'P404', component: () => import('../page/404.vue') },
];
